### ISSUE TITLE
ag issue: negating patterns with '!' in .gitignore after using '*' 

### ISSUE THREAD

**Issue by yannickperrenet** [yannickperrenet/dotfiles#14]
Example `.gitignore`
```
# Ignore everything
*

# Except
!vim/
```
Now running `ag "text" .` will not search the `vim/` directory. In certain situations it is fine running `ag -U "text"` instead.

See: https://github.com/ggreer/the_silver_searcher/issues/168

**Comment by yannickperrenet** [comment]
Use `ripgrep` instead, which does not have this issue.

Reference: https://github.com/BurntSushi/ripgrep

**Comment by yannickperrenet** [comment]
Great feature comparison between `ack`, `ag` and `rg`: https://beyondgrep.com/feature-comparison/ (by the creator of `ack`).

**Comment by Integralist** [comment]
Thanks for the tip off towards `-U --skip-vcs-ignores` ❤️
