### ISSUE TITLE
Ack vim plugin: go to next search result

### ISSUE THREAD

**Issue by yannickperrenet** [yannickperrenet/dotfiles#17]
Instead of having to go via the quickfix window, it would be much better to have a mapping that does this.

**Comment by yannickperrenet** [comment]
An idea for the key that it is mapped to is the down arrow key.

**Comment by yannickperrenet** [comment]
@ricklamers What do you think?

**Comment by yannickperrenet** [comment]
I can just use `:cn` and `:cp` to go to the next and previous item respectively. Since I have not used it often yet, I don't see the need to create a mapping for it.

**Comment by ricklamers** [comment]
I agree with what @yannickperrenet said.
